# Profile : dev 
spring.profiles.active: dev

---

spring:
  profiles: dev
  datasource:


  # Change datasource to PostgreSQL 



  # Change to PostgreSQL 
    # url: jdbc:mysql://localhost:3306/chat_mysql_db 
    # username: root
    # password: password 
    testWhileIdle: true
    validationQuery: SELECT 1
    url: jdbc:postgresql://localhost:5432/learningtest 
    username: hien
    password: password 




# spring.jpa.hibernate.ddl-auto=create-drop




  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  session:
    store-type: redis  
  thymeleaf:
    cache: false
  messages:
    cache-seconds: 0
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: true





# Enable Flyway
flyway.enabled: true      
# Security config 
security.headers.cache: false 
# Server session timeout 
# server.port: 9009
server.session.timeout: 600




# Project properties 
ebook:
  chat:
    relay:
      host: localhost
      port: 61613




---

spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/ebook_chat
    username: root
    password: root
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
  data:
    redis:
      repositories:
        enabled: true

flyway.enabled: true

ebook:
  chat:
    relay:
      host: localhost
      port: 61613